### ISSUE TITLE
Voice Call Not Working using Android SDK

### ISSUE THREAD

**Issue by meet2011** [twilio/voice-quickstart-server-php#13]
I'm using android SDK to program voice to voice call using internet with the help of sample demo. Here are the steps that I have followed

1. Generate Access token using identity on two different devices with two different identities as "Mit12" and "Mit13"
2. Tap on Call Icon and input either of identity.

Both the steps works but i never get call on either of devices.

I have also set TwiML code on our server using PHP example and there is no error but it doesn't work. If i input phoneNumber instead of "Mit13" i get phone call not internet call.

Please suggest what should be corrected to resolve the problem.

**Comment by kbagchiGWC** [comment]
@meet2011 

Did "Mit12" and "Mit13" register successfully to receive incoming call? Can you confirm you have followed the steps described here https://github.com/twilio/voice-quickstart-android?

Please share the call sid of the outgoing call that did not reach the callee.

Thanks.

**Comment by meet2011** [comment]
Yes both identities were successfullly registered.

I have this Call SID
CA79f4c3df89cee01710531a9f411b0ed7

I can share the screenshot from TwiML->Call Logs

**Comment by kbagchiGWC** [comment]
Your TwiML it is malformed and resulted in [Error 13224](https://www.twilio.com/docs/api/errors/13224#:~:text=Warning%20%2D%2013224&text=This%20error%20occurs%20when%20the%20provided%20number%20is%20not%20in%20E.&text=This%20can%20also%20occur%20with,the%20phone%20number's%20local%20area.)
Below is the Twiml that was sent : 
```
<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Dial callerId="client:quick_start">Mitesh1113
        <Client>Mitesh1113</Client>
    </Dial>
</Response>
```
It should be:
```
<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Dial callerId="client:quick_start">
        <Client>Mitesh1113</Client>
    </Dial>
</Response>
```

**Comment by meet2011** [comment]
I'm following PHP sample that's already in the github. Is that wrong or I'm looking at wrong code?

https://github.com/twilio/voice-quickstart-server-php

**Comment by meet2011** [comment]
Please look now.

Call SID
CAf066ba11cdcbe5c2add3740e6a445db5

Why there are two logs at the same time?  Please check the attached screenshot.

I am still not able to get calls, it keeps on ringing.

Thanks
<img width="1190" alt="Screenshot 2020-12-03 at 7 13 37 PM" src="https://user-images.githubusercontent.com/12157876/101025630-dbdf9c80-359b-11eb-904f-61c91c9242da.png">

**Comment by meet2011** [comment]
@kbagchiGWC Can you tell what's wrong in above request?

**Comment by kbagchiGWC** [comment]
@meet2011 

Checked the backend, the notification was sent to he device registered with `client:Mitesh1113` identity. `SENT` status as `payload.latest_state` indicates it was sent successfully by Twilio. However, we did not see any incoming events in the voice-insights which means that it was not received ny a device. 

![image](https://user-images.githubusercontent.com/10856725/101559367-d3111100-3975-11eb-8f84-b335acc4acd1.png)

Please check if you are using the correct `google-services.json` file and the corresponding credential sid.

**Comment by meet2011** [comment]
Do you mean if push is not received then there won't be any incoming call?

**Comment by kbagchiGWC** [comment]
@meet2011 - incoming call notification is delivered through push notification. If your app is not correctly setup to receive push notification, incoming call will not work.

Please follow the [step by step ](https://github.com/twilio/voice-quickstart-android#twilio-voice-quickstart-for-android) getting started guide and let us know if you have any questions. 

For android sdk questions please create an issue [here](https://github.com/twilio/voice-quickstart-android/issues/new).
